In [5]:
import seaborn as sns

In [6]:
import pandas as pd

In [12]:
healthexp = sns.load_dataset('healthexp')

In [13]:
healthexp.head()

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

In [14]:
healthexp = pd.get_dummies(healthexp, dtype=int)

In [16]:
healthexp.head()

,Year,Spending_USD,Life_Expectancy,Country_Canada,Country_France,Country_Germany,Country_Great Britain,Country_Japan,Country_USA
0,1970,252.311,70.6,0,0,1,0,0,0
1,1970,192.143,72.2,0,1,0,0,0,0
2,1970,123.993,71.9,0,0,0,1,0,0
3,1970,150.437,72.0,0,0,0,0,1,0
4,1970,326.961,70.9,0,0,0,0,0,1

In [17]:
X = healthexp.drop(['Life_Expectancy'], axis=1)

In [18]:
y = healthexp['Life_Expectancy']

In [21]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
from sklearn.ensemble import RandomForestRegressor

In [25]:
rfr = RandomForestRegressor(random_state=42)

In [26]:
rfr.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [27]:
y_pred = rfr.predict(X_test)

In [28]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [29]:
mean_absolute_error(y_test, y_pred)

0.274527272727264

In [30]:
mean_squared_error(y_test, y_pred)

0.12436518181817355

In [31]:
r2_score(y_test, y_pred)

0.9898132982462418

In [33]:
!pip install optuna

Collecting optuna
  Obtaining dependency information for optuna from https://files.pythonhosted.org/packages/15/da/68883911855d8b4d521f9a370e4e6aab8232b91c1d8d5a8348c4680c6642/optuna-3.6.1-py3-none-any.whl.metadata
  Downloading optuna-3.6.1-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Obtaining dependency information for alembic>=1.5.0 from https://files.pythonhosted.org/packages/df/ed/c884465c33c25451e4a5cd4acad154c29e5341e3214e220e7f3478aa4b0d/alembic-1.13.2-py3-none-any.whl.metadata
  Downloading alembic-1.13.2-py3-none-any.whl.metadata (7.4 kB)
Collecting colorlog (from optuna)
  Obtaining dependency information for colorlog from https://files.pythonhosted.org/packages/f3/18/3e867ab37a24fdf073c1617b9c7830e06ec270b1ea4694a624038fc40a03/colorlog-6.8.2-py3-none-any.whl.metadata
  Downloading colorlog-6.8.2-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in c:\users\or shkuri\anaconda3\lib\site-packages (from optuna) (1.24.3)
Requirement already satisfied: packaging>=20.0 in c:\users\or shkuri\anaconda3\lib\site-packages (from optuna) (23.1)
Requirement already satisfied: sqlalchemy>=1.3.0 in c:\users\or shkuri\anaconda3\lib\site-packages (from optuna) (1.4.39)
Requirement already satisfied: tqdm in c:\users\or shkuri\anaconda3\lib\site-packages (from optuna) (4.65.0)
Requirement already satisfied: PyYAML in c:\users\or shkuri\anaconda3\lib\site-packages (from optuna) (6.0)
Collecting Mako (from alembic>=1.5.0->optuna)
  Obtaining dependency information for Mako from https://files.pythonhosted.org/packages/03/62/70f5a0c2dd208f9f3f2f9afd103aec42ee4d9ad2401d78342f75e9b8da36/Mako-1.3.5-py3-none-any.whl.metadata
  Downloading Mako-1.3.5-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4 in c:\users\or shkuri\anaconda3\lib\site-packages (from alembic>=1.5.0->optuna) (4.7.1)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\or shkuri\anaconda3\lib\site-packages (from sqlalchemy>=1.3.0->optuna) (2.0.1)
Requirement already satisfied: colorama in c:\users\or shkuri\anaconda3\lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\or shkuri\anaconda3\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (2.1.1)
Downloading optuna-3.6.1-py3-none-any.whl (380 kB)
   ---------------------------------------- 0.0/380.1 kB ? eta -:--:--
   --- ------------------------------------ 30.7/380.1 kB 1.3 MB/s eta 0:00:01
   ------- ------------------------------- 71.7/380.1 kB 975.2 kB/s eta 0:00:01
   ---------------- ----------------------- 153.6/380.1 kB 1.3 MB/s eta 0:00:01
   ------------------------------- -------- 297.0/380.1 kB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 380.1/380.1 kB 2.0 MB/s eta 0:00:00
Downloading alembic-1.13.2-py3-none-any.whl (232 kB)
   ---------------------------------------- 0.0/233.0 kB ? eta -:--:--
   --------------------------------------- 233.0/233.0 kB 13.9 MB/s eta 0:00:00
Downloading colorlog-6.8.2-py3-none-any.whl (11 kB)
Downloading Mako-1.3.5-py3-none-any.whl (78 kB)
   ---------------------------------------- 0.0/78.6 kB ? eta -:--:--
   ---------------------------------------- 78.6/78.6 kB ? eta 0:00:00
Installing collected packages: Mako, colorlog, alembic, optuna
Successfully installed Mako-1.3.5 alembic-1.13.2 colorlog-6.8.2 optuna-3.6.1

In [34]:
import optuna

In [35]:
from sklearn.model_selection import cross_val_score

In [ ]:
def objective(trial):
    n_estimators = trial.suggest_int('n_estimators', 100, 1000)
    max_depth = 
    min_samples_split = 
    min_samples_leaf =